services:  
  - type: web
    name: CDCS Clipboard
    runtime: node
    repo: https://github.com/Sophistiqq/cdcs-backend
    plan: free
    envVars:
    - key: BUN_VERSION
      value: 1.1.0
    region: oregon
    buildCommand: bun install
    startCommand: bun start
version: "1"
